version: '3'

services:

  frontend:
    image: ghcr.io/lerkasan/boanerges-frontend:${FRONTEND_TAG:-latest} # commit sha from environment variable    aws deploy get-deployment --deployment-id $DEPLOYMENT_ID  --query  ".deploymentInfo.revision.gitHubLocation.commitId" --output text
    restart: always
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
      - /var/cache/nginx
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
#    environment:
#      DOMAIN_NAME: ${DOMAIN_NAME:-lerkasan.net}
    ports:
      - "80:80"
    networks:
      app:
    depends_on:
      - backend

  backend:
    image: ghcr.io/lerkasan/boanerges-backend:${BACKEND_TAG:-latest} # commit sha from environment variable   aws deploy get-deployment --deployment-id $DEPLOYMENT_ID  --query  ".deploymentInfo.revision.gitHubLocation.commitId" --output text
    restart: always
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    environment:
      - DB_HOST
      - DB_PORT=3306
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
      - SPRING_SERVER_PORT=8080
    networks:
      app:

networks:
  app:
